version: "3"

services:
  mysql:
    image: mysql:8.0.17
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./docker/volumes/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/volumes/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/volumes/mysql/data:/var/lib/mysql
    ports:
      - 13307:3306
